version: '2'
services:
  php:
    extends:
      file: pusher-environment.yml
      service: pusher-environment
    image: oliverlundquist/php7:latest
    command: ["php", "ObservationController.php"]
    volumes:
      - .:/var/app/current
    networks:
      - php-app
  pusher:
    extends:
      file: pusher-environment.yml
      service: pusher-environment
    image: oliverlundquist/pusher-local-dev-server:latest
    ports:
      - "57003:57003" # PUSHER_WEB_PORT
      - "57004:57004" # PUSHER_SOCKET_PORT
    volumes:
      - .:/var/app/current
    networks:
      - php-app
networks:
  php-app:
    driver: bridge